version: '3.1'
volumes:
  dados:
networks:
  banco:
services:
  db:
    image: mysql:8.0
    container_name: soul_academy_db_mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # Volume dos dados
      - dados:/var/lib/mysql
    networks:
      - banco
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=soul_academy
      - MYSQL_USER=cleiton
      - MYSQL_PASSWORD=12345
    ports:
      - 3306:3306
